inherit_gem:
  groundwork-style:
    - rubocop.yml
    - rubocop_performance.yml
    - rubocop_rake.yml
    - rubocop_rails.yml
    - rubocop_rspec.yml

Rails/ApplicationJob:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - after
    - for
    - if
    - unless
    - when
    - with
    - without

