inherit_gem:
  groundwork-style:
    - rubocop.yml
    - rubocop_performance.yml
    - rubocop_rake.yml
    - rubocop_rails.yml
    - rubocop_rspec.yml

Rails/ApplicationJob:
  Enabled: false

# This projects uses before(:all) a lot, for including the extension modules
# into the Rails classes they augment.
RSpec/BeforeAfterAll:
  Enabled: false

